import Articles from "./../components/landing/Articles/Index";
import Matches from "@/components/landing/Matches";
import Head from "next/head";
import Header from "@/components/common/Header/Index";
import Hero from "@/components/landing/Hero/Index";
import Footer from "@/components/common/Footer/Index";
import { Article } from "@/types/article";
import { getAllPublishedArticles } from "./../../lib/getAllPublishedArticles";

interface Props {
  articles: Article[];
}

export default function Home({ articles }: Props) {
  return (
    <>
      <Head>
        <title>Interista.pl</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_black.svg" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Hero articleName="Lorem ipsum rata tata  sg" articleId={2} />
        <Articles articles={articles} />
        <Matches />
        <Footer />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const articles = await getAllPublishedArticles();

  return {
    props: {
      articles,
    },
    revalidate: 1,
  };
};
