import Articles from "./../components/landing/Articles/Index";
import Matches from "@/components/landing/Matches";
import Head from "next/head";
import Header from "@/components/landing/Header/Index";
import Hero from "@/components/landing/Hero/Index";
import Footer from "@/components/common/Footer/Index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_black.svg" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Header />
        <Hero articleName="Lorem ipsum rata tata  sg" articleId={2} />
        <Articles />
        <Matches />
        <Footer />
      </main>
    </>
  );
}
